var LANG_PACK = {
    'zh-CN': {
        appTitle: '陽光群島巴士路綫查詢系統',
        funcTitle1: '請選擇您需要的功能，開始您的旅程',
        zhBtn: '中文',
        enBtn: 'English',
        funcTitle: '功能選擇',
        routeSelect: '路綫站點查詢',
        routeSelectDesc: '查詢陽光群島巴士站點信息',
        updateLog: '更新日志',
        updateLogDesc: '查看版本更新内容和優化記錄',
        backBtn: '返回',
        inputTitle: '綫路編號輸入',
        routeNumberLabel: '綫路編號',
        inputPlaceholder: '輸入綫路編號',
        deleteBtn: '删除',
        clearBtn: '清空',
        suggestTitle: '匹配的綫路',
        emptySuggest: '請輸入綫路編號',
        noMatchSuggest: '沒有匹配的綫路',
        stopPageTitle: '站点信息',
        stopPageTitleWithRoute: '站点信息',
        timetableBtn: '查看時間表',
        firstBus: '首班車',
        lastBus: '末班車',
        intervalTitle: '間隔',
        emptyTimetable: '沒有時間表數據',
        prevPage: '上一頁',
        nextPage: '下一頁',
        pageLabel: '第 {current} 頁 / 共 {total} 頁',
        directionA: '往',
        directionB: '往',
        loopDirection: '循環綫',
        driveDirection: '往: ',
        viaDirection: '途徑站點',
        routeType: '綫路类型: ',
        tempClose: '暫時停用',
        stopNumber: '序號',
        stopName: '名稱',
        direction: '目前方向',
        operationTime: '{route} 時間表',
        outbound: '去程 (A方向)',
        inbound: '回程 (B方向)',
        loop: '循環綫',
        switchTo: '換爲',
        noInformation: '沒有信息',
        normalShift: '常規',
        specialShift1: '特殊班次1',
        specialShift2: '特殊班次2',
        specialShift3: '特殊班次3',
        minutesPerTrip: '分鐘/班',
        viaLabel: '途經: ',
        tempCloseReason: '原因: ',
        appVersion: '版本',
        loadingTitle: '加载中...',
        initFailed: '請重新加載',
        confirm: '確認',
        cancel: '取消',
        circularLine: '(循環綫)',
        logVersion: '版本',
        logTime: '更新時間',
        logTitle: '更新日志',
        logEmpty: '沒有更新日志數據',
        logContent: '更新内容',
        switchDirection: '切換方向',
        shiftNormal: '常規班次',
        shiftSpecial: '特別班次',
        timeSlot: '時段',
        interval: '間隔',
        logAdded: '新增功能',
        logFixed: '問題修復',
        logRemoved: '移除内容',
        logRevamped: '優化内容',
        logImprovements: '其他改進',
        noShiftInformation: '沒有班次信息',
        turningPoint: '轉折點',
        shiftName: '班次',
        unknownRoute: '未知路綫',
        searchStopPlaceholder: '找站點',
        unlockLevelReq: 'Lv.{level}',
        typeOvernight: '通宵',
        typeSightseeing: '觀光',
        typeEvent: '活動',
        typeFestival: '節日',
        typeCrewShuttle: '工作人員接駁',
        typeUniversity: '大學',
        typeExpress: '特快',
        'typeLimited-stop': '半直通',
        typeCircular: '循環',
        typeSpecialDeparture: '特別班次',
        typeStadium: '體育場',
        typeCentralAxis: 'Central Axis',
        typeCityStepped: 'CityStepped',
        stationSearcher: '站點搜尋器',
        stationSearcherHeader: '所有站點列表',
        version: 'Website System v0.3.1',
        brand: '陽光群島'
    },
    'en-US': {
        appTitle: 'Sunshine Islands Bus Route Inquiry System',
        funcTitle1: 'Please select the features you need and begin your journey',
        zhBtn: 'Chinese',
        enBtn: 'English',
        funcTitle: 'Function Selection',
        routeSelect: 'Route & Stop Inquiry',
        routeSelectDesc: 'Inquire SIBS route stops',
        updateLog: 'Update Log',
        updateLogDesc: 'View version update content and optimization records',
        backBtn: 'Back',
        inputTitle: 'Route Number Input',
        routeNumberLabel: 'Route Number',
        inputPlaceholder: 'Click to enter route number',
        deleteBtn: 'Delete',
        clearBtn: 'Clear',
        suggestTitle: 'Matched Routes',
        emptySuggest: 'Please enter route number and select from suggestions',
        noMatchSuggest: 'No matching routes, please check input',
        stopPageTitle: 'Stop Information',
        stopPageTitleWithRoute: 'Stop Information ',
        timetableBtn: 'View Operation Time',
        firstBus: 'First Bus',
        lastBus: 'Last Bus',
        intervalTitle: 'Departure Interval',
        emptyTimetable: 'No operation time data',
        prevPage: 'Previous Page',
        nextPage: 'Next Page',
        pageLabel: 'Page {current} / Total {total} Pages',
        directionA: 'to',
        directionB: 'to',
        loopDirection: 'Loop Direction',
        driveDirection: 'Direction: ',
        viaDirection: 'Via Direction: ',
        routeType: 'Route Type: ',
        tempClose: 'Temporarily Closed',
        stopNumber: 'Stop Number',
        stopName: 'Stop Name',
        direction: 'Current Direction',
        operationTime: '{route} Operation Time',
        outbound: 'Outbound (Direction A)',
        inbound: 'Inbound (Direction B)',
        loop: 'Loop',
        switchTo: 'Switch to',
        noInformation: 'No Information',
        normalShift: 'Regular Service',
        specialShift1: 'Special Service 1',
        specialShift2: 'Special Service 2',
        specialShift3: 'Special Service 3',
        minutesPerTrip: 'mins/trip',
        viaLabel: 'Via: ',
        tempCloseReason: 'Closure Reason: ',
        appVersion: 'Version',
        loadingTitle: 'Loading...',
        initFailed: 'App initialization failed, please refresh and try again!',
        confirm: 'Confirm',
        cancel: 'Cancel',
        circularLine: '(Circular)',
        // 新增更新日志相关翻译
        logVersion: 'Version',
        logTime: 'Update Time',
        logTitle: 'Update Log',
        logEmpty: 'No update log data available',
        logContent: 'Update Content',
        // 時間表面板相关
        switchDirection: 'Switch Direction',
        shiftNormal: 'Regular Service',
        shiftSpecial: 'Special Service',
        timeSlot: 'Time Slot',
        interval: 'Interval',
        logAdded: 'Added',
        logFixed: 'Fixed',
        logRemoved: 'Removed',
        logRevamped: 'Revamped',
        logImprovements: 'Improvements',
        noShiftInformation: 'No shift information',
        turningPoint: 'Turning Point',
        shiftName: 'Shift Name',
        unknownRoute: 'Unknown route',
        searchStopPlaceholder: 'Search stops',
        unlockLevelReq: 'Lv.{level}',
        typeOvernight: 'Overnight',
        typeSightseeing: 'Sightseeing',
        typeEvent: 'Event',
        typeFestival: 'Festival',
        typeCrewShuttle: 'Crew Shuttle',
        typeUniversity: 'University',
        typeExpress: 'Express',
        'typeLimited-stop': 'Limited-stop',
        typeCircular: 'Circular',
        typeSpecialDeparture: 'Special Departure',
        typeStadium: 'Stadium',
        typeCentralAxis: 'Central Axis',
        typeCityStepped: 'CityStepped',
        stationSearcher: 'Station Searcher',
        stationSearcherHeader: 'All Stations List',
        version: 'Website System v0.3.1',
        brand: 'Sunshine Islands'
    }
};
