var LANG_PACK = {
    'zh-CN': {
        // sibsweb_page2
        brand: '陽光群島',
        version: 'Website System v0.4.1',
        appTitle: '查詢系統',
        funcTitle1: '選擇您的功能',
        routeSelect: '路綫查詢',
        routeSelectDesc: '查詢路綫信息',
        updateLog: '更新日志',
        updateLogDesc: '查看版本更新内容',
        stationSearcher: '站點查詢',
        stationSearcherDec: '查詢站點信息',
        p2pSearch: '點對點搜尋 BETA',
        p2pSearchDesc: '智能規劃最佳乘車路線',


        // sibsweb_page3L
        unlockLevelReq: 'Lv.{level}',


        // sibsweb_page3R
        inputTitle: '路綫',
        suggestTitle: '匹配的綫路',
        inputPlaceholder: '輸入路綫號碼',
        deleteBtn: '删除',
        clearBtn: '清空',


        // sibsweb_page4
        stopPageTitleWithRoute: '路綫站點信息',
        timetableBtn: '查看時間表',
        emptyTimetable: '沒有時間表數據',
        viaDirection: '途徑站點',
        stopNumber: '序號',
        stopName: '名稱',
        nearbyRoutes: '同站路綫',
        pageLabel: '第 {current} 頁 / 共 {total} 頁',


        // sibsweb_page5
        logTitle: '更新日志',
        logEmpty: '沒有更新日志數據',
        logVersion: '版本',
        logAdded: '新增功能',
        logFixed: '問題修復',
        logRemoved: '移除内容',
        logRevamped: '優化内容',
        logImprovements: '其他改進',


        // sibsweb_page6
        searchStopPlaceholder: '輸入路綫編號、路綫代碼或巴士站名',
        routeResult: '路綫結果',
        stopResult: '站點結果',
        noSearch: '找不到符合「{keyword}」的結果',


        // type
        typeOvernight: '通宵',
        typeSightseeing: '觀光',
        typeEvent: '活動',
        typeFestival: '節日',
        typeCrewShuttle: '工作人員接駁',
        typeUniversity: '大學',
        typeExpress: '特快',
        'typeLimited-stop': '半直通',
        typeCircular: '循環',
        typeSpecialDeparture: '特別班次',
        typeStadium: '體育場',
        typeCentralAxis: 'Central Axis',
        typeCityStepped: 'CityStepped',
        noShiftInformation: ' ',


        // settings
        zhBtn: '中文',
        enBtn: 'English',


        // tag
        loopDirection: '循環綫',
        turningPoint: '轉折點',
        tempClose: '暫時停用',
        normalShift: '常規',
        specialShift1: '特殊班次1',
        specialShift2: '特殊班次2',
        specialShift3: '特殊班次3',
        specialShift4: '特殊班次4',


        // sibsweb_page7 + sibsweb_p2p_detail
        p2pStartPlaceholder: '起點 (例如：陽光碼頭)',
        p2pEndPlaceholder: '目的地 (例如：陽光站)',
        p2pLessTransfer: '最少轉乘',
        p2pCheapest: '最便宜',
        p2pPlanRoute: '規劃路線',
        p2pQuickPick: '快速選擇站點',
        p2pBoardingPass: '路線詳情',
        p2pTotalFare: '總車資',
        p2pTransferAt: '在此站轉乘',
        p2pBoard: '上車',
        p2pAlight: '下車',
        p2pLoading: '正在規劃中...',
        p2pNoRoute: '找不到可適合的巴士路線。',
        p2pOptionCount: '已為您規劃最佳方案 ({count} 個選項)',
        p2pDirect: '直達',
        p2pTransferCount: '轉乘 {count} 次',
        p2pMinsFreq: '約 {time} 分鐘一班',
        p2pStopsCount: '經 {count} 站',


        // unknown
        funcTitle: '功能選擇',
        backBtn: '返回',
        routeNumberLabel: '路綫號碼',
        emptySuggest: '請輸入路綫號碼',
        noMatchSuggest: '沒有匹配的綫路',
        stopPageTitle: '站點信息',
        firstBus: '首班車',
        lastBus: '末班車',
        intervalTitle: '間隔',
        prevPage: '上一頁',
        nextPage: '下一頁',
        directionA: '往',
        directionB: '往',
        driveDirection: '往: ',
        routeType: '綫路类型: ',
        direction: '目前方向',
        operationTime: '{route} 時間表',
        outbound: '去程 (A方向)',
        inbound: '回程 (B方向)',
        loop: '循環綫',
        switchTo: '換爲',
        noInformation: '沒有信息',
        minutesPerTrip: '分鐘/班',
        viaLabel: '途經: ',
        tempCloseReason: '原因: ',
        loadingTitle: '加载中...',
        initFailed: '請重新加載',
        appVersion: '版本',
        confirm: '確認',
        cancel: '取消',
        circularLine: '(循環綫)',
        logTime: '更新時間',
        logContent: '更新内容',
        switchDirection: '切換方向',
        shiftNormal: '常規班次',
        shiftSpecial: '特別班次',
        timeSlot: '時段',
        interval: '間隔',
        shiftName: '班次',
        unknownRoute: '未知路綫',
        randomRoute: '隨機',
        backToHome: '返回主頁',
        reloadPage: '重新加載',
        settings: '設定'
    },
    'en-US': {
        appTitle: 'Inquiry System',
        funcTitle1: 'Select the features',
        zhBtn: 'Chinese',
        enBtn: 'English',
        funcTitle: 'Function Selection',
        routeSelect: 'Route Inquiry',
        routeSelectDesc: 'Inquire bus routes',
        updateLog: 'Update Log',
        updateLogDesc: 'View version update content',
        backBtn: 'Back',
        inputTitle: 'Route',
        routeNumberLabel: 'Route Number',
        inputPlaceholder: 'Input Route Number',
        deleteBtn: 'Delete',
        clearBtn: 'Clear',
        suggestTitle: 'Matched Routes',
        emptySuggest: 'Please enter route number and select from suggestions',
        noMatchSuggest: 'No matching routes, please check input',
        stopPageTitle: 'Stop Information',
        stopPageTitleWithRoute: 'Route + Stops Information',
        timetableBtn: 'View Operation Time',
        firstBus: 'First Bus',
        lastBus: 'Last Bus',
        intervalTitle: 'Departure Interval',
        emptyTimetable: 'No operation time data',
        prevPage: 'Previous Page',
        nextPage: 'Next Page',
        pageLabel: 'Page {current} / Total {total} Pages',
        directionA: 'to',
        directionB: 'to',
        loopDirection: 'Loop Direction',
        driveDirection: 'Direction: ',
        viaDirection: 'Via Direction: ',
        routeType: 'Route Type: ',
        tempClose: 'Temporarily Closed',
        stopNumber: 'Stop Number',
        stopName: 'Stop Name',
        direction: 'Current Direction',
        operationTime: '{route} Operation Time',
        outbound: 'Outbound (Direction A)',
        inbound: 'Inbound (Direction B)',
        loop: 'Loop',
        switchTo: 'Switch to',
        noInformation: 'No Information',
        normalShift: 'Regular Service',
        specialShift1: 'Special Service 1',
        specialShift2: 'Special Service 2',
        specialShift3: 'Special Service 3',
        specialShift4: 'Special Service 4',
        minutesPerTrip: 'mins/trip',
        viaLabel: 'Via: ',
        tempCloseReason: 'Closure Reason: ',
        appVersion: 'Version',
        loadingTitle: 'Loading...',
        initFailed: 'Initialization failed, please refresh and try again!',
        confirm: 'Confirm',
        cancel: 'Cancel',
        circularLine: '(Circular)',
        logVersion: 'Version',
        logTime: 'Update Time',
        logTitle: 'Update Log',
        logEmpty: 'No update log data available',
        logContent: 'Update Content',
        switchDirection: 'Switch Direction',
        shiftNormal: 'Regular Service',
        shiftSpecial: 'Special Service',
        timeSlot: 'Time Slot',
        interval: 'Interval',
        logAdded: 'Added',
        logFixed: 'Fixed',
        logRemoved: 'Removed',
        logRevamped: 'Revamped',
        logImprovements: 'Improvements',
        noShiftInformation: ' ',
        turningPoint: 'Turning Point',
        shiftName: 'Shift Name',
        unknownRoute: 'Unknown route',
        unlockLevelReq: 'Lv.{level}',
        typeOvernight: 'Overnight',
        typeSightseeing: 'Sightseeing',
        typeEvent: 'Event',
        typeFestival: 'Festival',
        typeCrewShuttle: 'Crew Shuttle',
        typeUniversity: 'University',
        typeExpress: 'Express',
        'typeLimited-stop': 'Limited-stop',
        typeCircular: 'Circular',
        typeSpecialDeparture: 'Special Departure',
        typeStadium: 'Stadium',
        typeCentralAxis: 'Central Axis',
        typeCityStepped: 'CityStepped',
        stationSearcher: 'Stops Inquiry',
        searchStopPlaceholder: 'Filter by route number, code, or bus stop',
        stationSearcherDec: 'Inquire bus stops',
        version: 'Website System v0.4.1',
        brand: 'Sunshine Islands',
        nearbyRoutes: 'Nearby Routes',
        randomRoute: 'Random',
        backToHome: 'Back to Home',
        reloadPage: 'Reload Page',
        settings: 'Settings',

        p2pSearch: 'Point-to-Point Search BETA',
        p2pSearchDesc: 'Smart route planner',
        p2pStartPlaceholder: 'Origin (e.g., Sunshine Pier)',
        p2pEndPlaceholder: 'Destination (e.g., Sunshine Station)',
        p2pLessTransfer: 'Less Transfers',
        p2pCheapest: 'Cheapest',
        p2pPlanRoute: 'Plan Route',
        p2pQuickPick: 'Quick Pick Stops',
        p2pBoardingPass: 'Route Details',
        p2pTotalFare: 'Total Fare',
        p2pTransferAt: 'Transfer at this stop',
        p2pBoard: 'Board',
        p2pAlight: 'Alight',
        p2pLoading: 'Planning the route...',
        p2pNoRoute: 'No available routes found.',
        p2pOptionCount: 'Found best routes ({count} options)',
        p2pDirect: 'Direct',
        p2pTransferCount: '{count} transfers',
        p2pMinsFreq: 'Every {time} mins',
        p2pStopsCount: '{count} stops',
        routeResult: 'Route Results',
        stopResult: 'Stop Results',
        noSearch: 'No results found for {keyword}'
    }
};