// lang.js
var LANG_PACK = {
    'zh-CN': {
        appTitle: '旅遊路綫查詢系統',
        zhBtn: '中文',
        enBtn: 'English',
        backBtn: '返回',
        routeNumberLabel: '路綫',
        deleteBtn: '删除',
        clearBtn: '清空',
        suggestTitle: '匹配的綫路',
        emptySuggest: '请输入线路编号，从建议列表选择',
        noMatchSuggest: '暂无匹配的线路，请检查输入',
        stopPageTitle: '站点信息',
        stopPageTitleWithRoute: '站点信息',
        timetableBtn: '查看時間表',
        firstBus: '首班車',
        lastBus: '末班車',
        intervalTitle: '詳細班次',
        emptyTimetable: '暂无运营时间数据',
        prevPage: '上一頁',
        nextPage: '下一頁',
        pageLabel: '第 {current} 頁 / 共 {total} 頁',
        directionA: '切換至B方向',
        directionB: '切換至A方向',
        loopDirection: '循環綫',
        driveDirection: '路綫方向',
        viaDirection: '途經方向',
        routeType: '路綫類型',
        tempClose: '临时关闭',
        stopNumber: '站点序号',
        stopName: '站点名称',
        direction: '目前方向',
        operationTime: '路綫 {route} 時間表',
        outbound: '去程 (A方向)',
        inbound: '回程 (B方向)',
        loop: '循環綫',
        switchTo: '換爲',
        noInformation: '-',
        normalShift: '常規班次',
        minutesPerTrip: '分鐘/班',
        viaLabel: '途經: ',
        tempCloseReason: '关闭原因: ',
        appVersion: '版本',
        loadingTitle: '加载中...',
        initFailed: '应用加载失败，请刷新页面重试！',
        confirm: '确认',
        cancel: '取消',
        circularLine: '(循環綫)',
        // 运营时间面板相关
        switchDirection: '切換方向',
        shiftNormal: '常规班次',
        shiftSpecial: '特殊班次',
        timeSlot: '时段',
        interval: '间隔',
        noShiftInformation: '暂无班次信息',
        turningPoint: '轉折點',
        shiftName: '班次',
        unknownRoute: '未知路綫'
    },
    'en-US': {
        appTitle: 'Travel Bus Route Inquiry System',
        zhBtn: 'Chinese',
        enBtn: 'English',
        backBtn: 'Back',
        routeNumberLabel: 'Route',
        deleteBtn: 'Delete',
        clearBtn: 'Clear',
        suggestTitle: 'Matched Routes',
        emptySuggest: 'Please enter route number and select from suggestions',
        noMatchSuggest: 'No matching routes, please check input',
        stopPageTitle: 'Stop Information',
        stopPageTitleWithRoute: 'Stop Information ',
        timetableBtn: 'View Operation Time',
        firstBus: 'First Bus',
        lastBus: 'Last Bus',
        intervalTitle: 'Departure Interval',
        emptyTimetable: 'No operation time data',
        prevPage: 'Previous Page',
        nextPage: 'Next Page',
        pageLabel: 'Page {current} / Total {total} Pages',
        directionA: 'Switch to B Direction',
        directionB: 'Switch to A Direction',
        loopDirection: 'Loop Direction',
        driveDirection: 'Direction',
        viaDirection: 'Via Direction',
        routeType: 'Route Type',
        tempClose: 'Temporarily Closed',
        stopNumber: 'Stop Number',
        stopName: 'Stop Name',
        direction: 'Current Direction',
        operationTime: 'Route {route} Operation Time',
        outbound: 'Outbound (Direction A)',
        inbound: 'Inbound (Direction B)',
        loop: 'Loop',
        switchTo: 'Switch to',
        noInformation: '-',
        normalShift: 'Regular Service',
        specialShift1: 'Special Service 1',
        specialShift2: 'Special Service 2',
        specialShift3: 'Special Service 3',
        minutesPerTrip: 'mins/trip',
        viaLabel: 'Via: ',
        tempCloseReason: 'Closure Reason: ',
        appVersion: 'Version',
        loadingTitle: 'Loading...',
        initFailed: 'App initialization failed, please refresh and try again!',
        confirm: 'Confirm',
        cancel: 'Cancel',
        circularLine: '(Circular)',
        // 运营时间面板相关
        switchDirection: 'Switch Direction',
        shiftNormal: 'Regular Service',
        shiftSpecial: 'Special Service',
        timeSlot: 'Time Slot',
        interval: 'Interval',
        noShiftInformation: 'No shift information',
        turningPoint: 'Turning Point',
        shiftName: 'Shift Name',
        unknownRoute: 'Unknown route'
    }
};